# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MySavings-IOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MySavings-IOS
	pod 'PhoneNumberKit', :git => 'https://github.com/marmelroy/PhoneNumberKit'

end
